[tool.poetry]
name = "lib_b"
version = "0.1.0"
description = ""
authors = []
packages = [{include = "lib_b"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.8"
